.IX Title "RSHTTPD 1"
.TH RSHTTPD 1 "2021-06-12" "rshttpd"
.if n .ad l
.nh
.SH "NAME"
rshttpd \- HTTP (web) server written in Rust
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
rshttpd IPADDRESS

.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
Does not work over SSL, so maybe use stunnel for that.

.SH "OPTIONS"
.IX Header "OPTIONS"
IPADDRESS \- Address to bind service to.
.SH "ENVIRONMENT"
.IX Header "ENVIRONMENT"
Edit /etc/rshttpd.conf for configuration.
.SH "AUTHOR"
.IX Header "AUTHOR"
\fB<https://github.com/coreydunn\fR>
.SH "COPYRIGHT"
.IX Header "COPYRIGHT"
.PP
Copyright stuff here.
